from .settings import (
    BASE_URL, LOGIN_URL, DISCREPANCIES_URL,
    ADMIN_USERNAME, ADMIN_PASSWORD,
    API_BASE, ENDPOINTS,
    HEADLESS, DEFAULT_TIMEOUT, SLOW_MO,
    DEFAULT_VIEWPORT, BROWSER_CHANNEL,
    DEFAULT_CENTER_CODE,
)
